# Generated by Django 4.0 on 2021-12-29 15:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Clientes',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=100, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Proyectos',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('projectName', models.CharField(max_length=100, unique=True)),
                ('descripcion', models.CharField(max_length=200)),
                ('fechaIngreso', models.DateTimeField(blank=True, null=True)),
                ('fechaSalida', models.DateTimeField(blank=True, null=True)),
                ('responsable', models.CharField(max_length=200)),
                ('clientesId', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='clientesId', to='projectsApp.clientes')),
            ],
        ),
    ]
